name: Sync Dev(main) Branch to Krampoline test Repo

on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    # 원본 레포지토리에서 소스 코드를 가져오기
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        ref: main

    # 개인 레포지토리로 소스 코드를 복사하여 푸시하기
    - name: Push to krampoline test repo
      env:
        KRAM_REPO: 42kko/fork_dodoFE  # 개인 레포지토리 설정
        TOKEN: ${{ secrets.TEST }}  # 개인 액세스 토큰 설정
      run: |
        git remote add personal https://$TOKEN@github.com/42kko/fork_dodoFE.git
        git push personal main
