# .github/workflows/sync-to-fork.yml
name: Sync to fork_dodoFE Repository

on:
  push:
    branches:
      - main  # 원본 레포지토리의 브랜치 이름입니다.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 원본 레포지토리의 코드를 가져오기
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST }} # 원본 레포지토리 액세스 토큰

      # 2. 타겟 레포지토리에 복사 및 푸시
      - name: Push to target repository
        env:
          TARGET_REPO: https://github.com/42kko/fork_dodoFE.git
          TARGET_REPO_TOKEN: ${{ secrets.TEST }} # 타겟 레포지토리 액세스 토큰
        run: |
          git remote set-url origin https://$TARGET_REPO_TOKEN@github.com/42kko/fork_dodoFE.git
          git add .
          git commit -m "Sync from source repository"
          git push origin main -f
