# .github/workflows/sync-to-fork.yml
name: Sync to fork_dodoFE Repository

on:
  push:
    branches:
      - main  # 원본 레포지토리의 브랜치 이름을 설정합니다.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST }} # 원본 레포지토리 액세스 토큰

      - name: Clean repository for rsync-style sync
        run: |
          rm -rf .git
          git init
          git remote add origin https://$TARGET_REPO_TOKEN@github.com/42kko/fork_dodoFE.git
          git add .
          git commit -m "Syncing updates from source repository"

      - name: Push to target repository
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TEST }}
        run: |
          git push -u origin main -f
