name: Sync to fork_dodoFE Repository

on:
  push:
    branches:
      - main  # 원본 레포지토리의 브랜치 이름입니다.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST }} # 원본 레포지토리 액세스 토큰

      - name: Push to target repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TEST }} # 타겟 레포지토리 액세스 토큰
        with:
          source-directory: '.' # 현재 레포지토리 전체
          destination-github-username: '42kko'
          destination-repository-name: 'fork_dodoFE'
          target-branch: main
          commit-message: "Sync from source repository"
