# .github/workflows/sync-to-fork.yml
name: Sync to fork_dodoFE Repository

on:
  push:
    branches:
      - main  # 원본 레포지토리의 브랜치 이름을 설정합니다.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST }} # 원본 레포지토리 액세스 토큰

      - name: Set up Git
        run: |
          git config --global user.name '42kko'
          git config --global user.email 'rhrudgns159@naver.com'

      - name: Push to target repository
        env:
          TARGET_REPO: git@github.com:42kko/fork_dodoFE.git # 타겟 레포지토리 주소
        run: |
          git remote add target $TARGET_REPO
          git push target main:main -f # 타겟 브랜치로 푸시
