# .github/workflows/sync-to-fork.yml
name: Sync to fork_dodoFE Repository

on:
  push:
    branches:
      - main  # 원본 레포지토리의 브랜치 이름을 설정합니다.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST }} # 원본 레포지토리 액세스 토큰

      - name: Set up Git
        run: |
          git config --global user.name '42kko'

      - name: Push to target repository
        env:
          TARGET_REPO: https://github.com/42kko/fork_dodoFE.git # HTTPS URL로 변경
          TARGET_REPO_TOKEN: ${{ secrets.TEST }} # 타겟 레포지토리 액세스 토큰
        run: |
          git remote add target https://$TARGET_REPO_TOKEN@github.com/42kko/fork_dodoFE.git
          git push target main:main -f
