name: Krampoline Notification

on: 
  push:
    branches:
      - main

jobs:
  noti:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Last Push Info from Original Repo
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }} # 원본 레포 정보에 접근하기 위한 Token
        ORIGINAL_REPO: "DoDoDocs/dododocs-backend" # 원본 레포 이름
        ORIGINAL_BRANCH: "main" # 원본 레포의 브랜치 이름
      run: |
        # GitHub API로 원본 레포의 브랜치 정보 가져오기
        LAST_COMMIT_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/$ORIGINAL_REPO/branches/$ORIGINAL_BRANCH")

        # JSON 파싱으로 필요한 데이터 추출
        LAST_COMMIT_SHA=$(echo "$LAST_COMMIT_INFO" | jq -r '.commit.sha')
        LAST_COMMIT_MESSAGE=$(echo "$LAST_COMMIT_INFO" | jq -r '.commit.commit.message')
        LAST_COMMIT_AUTHOR=$(echo "$LAST_COMMIT_INFO" | jq -r '.commit.commit.author.name')

        # 환경변수 설정
        echo "LAST_COMMIT_SHA=$LAST_COMMIT_SHA" >> $GITHUB_ENV
        echo "LAST_COMMIT_MESSAGE=$LAST_COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "LAST_COMMIT_AUTHOR=$LAST_COMMIT_AUTHOR" >> $GITHUB_ENV

    - name: Debug Updated Variables
      run: |
        echo "Last Commit SHA: $LAST_COMMIT_SHA"
        echo "Last Commit Message: $LAST_COMMIT_MESSAGE"
        echo "Last Commit Author: $LAST_COMMIT_AUTHOR"

    - name: Send Discord Webhook
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_FULLSTACK }}
      run: |
        # Discord Webhook으로 데이터 전송
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [
              {
                "color": 16739652,
                "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'",
                "title": "❗️ Remind : 크램폴린123 CI/CD ❗️",
                "description": "크램폴린에서 D2Hub 빌드와 Kargo 배포를 진행해주세요.\n[여기](https://krampoline-ide.kakao.com/organization/org_ffYH4PrzrR6et39c2k/dashboard)를 눌러 크램폴린IDE로 들어가세요!",
                "fields": [
                  {
                    "name": "Repository",
                    "value": "[${{ env.ORIGINAL_REPO }}](https://github.com/${{ env.ORIGINAL_REPO }})",
                    "inline": true
                  },
                  {
                    "name": "Ref",
                    "value": "refs/heads/${{ env.ORIGINAL_BRANCH }}",
                    "inline": true
                  },
                  {
                    "name": "Last Commit",
                    "value": "[`${{ env.LAST_COMMIT_SHA:0:7 }}`](https://github.com/${{ env.ORIGINAL_REPO }}/commit/${{ env.LAST_COMMIT_SHA }})\n${{ env.LAST_COMMIT_MESSAGE }}",
                    "inline": false
                  },
                  {
                    "name": "Triggered by",
                    "value": "${{ env.LAST_COMMIT_AUTHOR }}",
                    "inline": true
                  }
                ]
              }
            ]
          }' \
          "$DISCORD_WEBHOOK_URL"
