name: Krampoline Notification

on: 
  push:
    branches:
      - main

jobs:
  noti:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord Webhook
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_FULLSTACK }}
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [
              {
                "color": 16739652,
                "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'",
                "title": "❗️ Remind : 크램폴린 CI/CD ❗️",
                "description": "크램폴린에서 D2Hub 빌드와 Kargo 배포를 진행해주세요.\n[여기](https://krampoline-ide.kakao.com/organization/org_ffYH4PrzrR6et39c2k/dashboard)를 눌러 크램폴린IDE로 들어가세요!",
                "fields": [
                  {
                    "name": "Repository",
                    "value": "[${GITHUB_REPOSITORY}](https://github.com/${GITHUB_REPOSITORY})",
                    "inline": true
                  },
                  {
                    "name": "Ref",
                    "value": "${GITHUB_REF}",
                    "inline": true
                  },
                  {
                    "name": "Event - ${GITHUB_EVENT_NAME}",
                    "value": "[`${GITHUB_SHA:0:7}`](https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}) ${GITHUB_EVENT_NAME}",
                    "inline": false
                  },
                  {
                    "name": "Triggered by",
                    "value": "${GITHUB_ACTOR}",
                    "inline": true
                  },
                  {
                    "name": "Workflow",
                    "value": "[${GITHUB_WORKFLOW}](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})",
                    "inline": true
                  }
                ]
              }
            ]
          }' \
          "$DISCORD_WEBHOOK_URL"
