name: Sync Trigger Fix

on: 
  push:
    branches:
      - main

jobs:
  fetch-original-trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Last Push Info from Original Repo
      env:
        GITHUB_TOKEN: ${{ secrets.KRAMPOLINE_TESTREPOKEY }}
        ORIGINAL_REPO: "DoDoDocs/dododocs-backend" # 원본 레포 이름
        ORIGINAL_BRANCH: "main" # 원본 레포의 브랜치 이름
      run: |
        # 원본 레포의 main 브랜치 정보 가져오기
        LAST_COMMIT_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/$ORIGINAL_REPO/branches/$ORIGINAL_BRANCH")

        # JSON 데이터 파싱
        LAST_COMMIT_SHA=$(echo "$LAST_COMMIT_INFO" | jq -r '.commit.sha')
        LAST_COMMIT_MESSAGE=$(echo "$LAST_COMMIT_INFO" | jq -r '.commit.commit.message')
        LAST_COMMIT_AUTHOR=$(echo "$LAST_COMMIT_INFO" | jq -r '.commit.commit.author.name')

        # 환경변수 덮어쓰기
        echo "GITHUB_SHA=$LAST_COMMIT_SHA" >> $GITHUB_ENV
        echo "GITHUB_ACTOR=$LAST_COMMIT_AUTHOR" >> $GITHUB_ENV
        echo "GITHUB_REF=refs/heads/$ORIGINAL_BRANCH" >> $GITHUB_ENV

    - name: Debug Updated Variables
      run: |
        echo "Commit SHA: $GITHUB_SHA"
        echo "Actor: $GITHUB_ACTOR"
        echo "Ref: $GITHUB_REF"
        echo "====="
        env

    - name: Send Corrected Notification
      uses: sarisia/actions-status-discord@v1.15.0
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_FULLSTACK }}
        title: "❗️ Corrected Trigger Information ❗️"
        description: |
          Repository: DoDoDocs/dododocs-backend
          Branch: main
          Commit SHA: ${{ env.GITHUB_SHA }}
          Actor: ${{ env.GITHUB_ACTOR }}
        color: 0xff6d44
